# Generated by Django 2.0.7 on 2020-10-02 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0004_auto_20201002_1739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='address',
            field=models.CharField(default='Your Address', max_length=50),
        ),
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.TextField(default='Your Bio', max_length=50),
        ),
        migrations.AlterField(
            model_name='profile',
            name='education',
            field=models.CharField(default='Your Education', max_length=20),
        ),
    ]
